version: "3"
services:
  geth:
    image: ethereum/client-go:v1.10.26
    ports:
      - "8545:8545"
    command: >
      --miner.gaslimit 12000000
      --dev.gaslimit 20000000
      --http 
      --http.api personal,eth,net,web3,debug
      --http.vhosts '*,localhost,host.docker.internal' 
      --http.addr "0.0.0.0"
      --ignore-legacy-receipts 
      --allow-insecure-unlock 
      --rpc.allow-unprotected-txs
      --dev
      --verbosity 2
      --nodiscover 
      --maxpeers 0 
      --mine 
      --miner.threads 1
      --networkid 1337

  bundler:
    image: transeptorlabs/bundler:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: >
      --port 3000
      --network http://host.docker.internal:8545
      --txMode base
      --httpApi web3,eth,debug
      --auto
      --autoBundleInterval 12000